export { Main } from "./main/Main.async";
export { News } from "./news/News.async";
export { Vacancy } from "./vacancy/Vacancy.async";
export { BayTash } from "./baytash/BayTash.async";
export { Beton } from "./beton/Beton.async";
export { Sand } from "./sand/Sand.async";
export { Complexe } from "./complexe/Complexe.async";
export { Error } from "./error/Error.async";
export { Stoodin } from "./stoodin/Stoodin.async";
